target-version = "py311"

[lint]
select = [
    "B007",
    "B014",
    "C",
    "D",
    "E",
    "F",
    "ICN001",
    "PGH004",
    "PLC0414",
    "SIM105",
    "SIM117",
    "SIM118",
    "SIM201",
    "SIM212",
    "SIM300",
    "SIM401",
    "T20",
    "TRY004",
    "RUF006",
    "UP",
    "W",
]
ignore = [
    "D202",
    "D203",
    "D213",
    "D404",
    "D406",
    "D407",
    "D411",
    "E501",
    "E731",
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.mccabe]
max-complexity = 25

[lint.pyupgrade]
keep-runtime-typing = true
